// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('./src/components/avatar/avatar.vue')['default']
    Button: typeof import('./src/components/button/button.vue')['default']
  }
}

export { }
