// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Sidebar: typeof import('~/layout/sidebar/sidebar.vue')['default']
    NavBar: typeof import('~/layout/navbar/navbar.vue')['default']
  }
}

export { }
